//======================================================================//
//																		//
//		Generated by gin-annotation (github.com/1-st/gin-annotation)	//
//																		//
//				***	you should call Route() manually ***				//
//																		//
//======================================================================//


package main

import (
	"github.com/1-st/gin-annotation/_example/simple/controller"
	"github.com/1-st/gin-annotation/_example/simple/middleware"
	"github.com/gin-gonic/gin"
)

func Route(e *gin.Engine) {
	api := e.Group("/api", middleware.Log)
	{
		v1 := api.Group("/v1")
		{
			v1.GET("/hello-world", middleware.Auth, controller.HelloWorld)
		}
	}
}
